name: Deploy Flask Application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask gunicorn

      - name: Run tests (optional)
        run: |
          # Add any test commands here if you have tests
          echo "No tests to run."

      - name: Deploy to Heroku (example)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          # Install Heroku CLI
          curl https://cli-assets.heroku.com/install.sh | sh
          # Login to Heroku
          heroku login --api-key $HEROKU_API_KEY
          # Deploy the app
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku main

      - name: Notify deployment status (optional)
        if: always()
        run: |
          # Add any notification logic here (e.g., Slack, email)
          echo "Deployment completed."
